ARC_COMMON_ATTR = ["Time"]
UNDER_WEIGHT = "Under Weight"
NORMAL_WEIGHT = "Normal Weight"
OVER_WEIGHT = "Over Weight"
MODERATELY_OBESE = "Moderately obese "
SEVERELY_OBESE = "Severely Obese"
VERY_SEVERELY_OBESE = "Very Severely Obese"
APP_NAME = "app.name"
BUCKET_NAME = "bucket.name"
PATH_PREFIX = "path.prefix"
FILE_PROTOCOL = "file.protocol"
SOURCE_FILE_NAME = "source.file.name"
OUTPUT_FILE_NAME = "output.file.name"
OUTPUT_FILE_PATH = "output.file.path"
OUTPUT_FILE_FORMAT = "output.file.format"
PROTOCOL_SEPERATOR = "/"
HEALTH_RISK = "Health risk"
MAL_NUT_RISK = "Malnutrition risk"
LOW_RISK="Low risk"
ENHANCED_RISK = "Enhanced risk"
MEDIUM_RISK = "Medium risk"
HIGH_RISK = "High risk"
VERY_HIGH_RISK = "Very high risk"
VALUE_40 = 40
VALUE_35 = 35
VALUE_30 = 30
VALUE_25 = 25
VALUE_18_5 = 18.5
VALUE_0 = 0

CSV = "csv"
JSON = "json"
